### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException:

### ISSUE THREAD

**Issue by tank777** [appmediation/android-example#2]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.appmediation.sdk.d.d.l()' on a null object reference
       at com.appmediation.sdk.a.a.notifyThatAdIsNowVisible(SourceFile:65)
       at com.appmediation.sdk.a.b.a(SourceFile:41)
       at com.appmediation.sdk.a.b$1$1.run(SourceFile:62)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by MertCelik** [comment]
Hello @tank777 ,
We are investigating the issue, meanwhile, could you please create a ticket from [this link](https://support.appmediation.com/portal/newticket) with problem description? This way we can track the issue in our system and update you with the progress via your email address.
